---
title: "temp_class_3"
author: "Jonathan"
date: "4/16/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("tidyverse")
library("nycflights13")
```

```{r}
flights %>% mutate(dep_on_time=case_when(dep_time<=sched_dep_time~1,
                                         dep_time>sched_dep_time~0))

flights %>% mutate(dep_on_time=case_when(dep_time<=sched_dep_time~1,
                                         TRUE~0))
```

```{r}
flights <- flights %>% unite("carrier_flight", carrier, flight)

flights %>% separate(carrier_flight, c("carrier", flight))
                     
```

```{r}
flights %>% arrange(dep_delay)
flights %>% arrange(-dep_delay)
flights %>% group_by(year, month, day) %>% arrange(dep_delay)

flights %>% top_n(1, dep_delay)
flights %>% top_n(-1, dep_delay)
flights %>% group_by(month) %>% top_n(-1, dep_delay)
```

```{r}
flights <- flights %>% mutate(origin=factor(origin, levels=c("EWR", "LGA", "JFK")))
flights <- flights %>% mutate(origin=factor(origin, levels=c("EWR", "LGA")))

flights <- flights %>% mutate(month=factor(month, levels=c("1", "2", "3")))
```

