---
title: "Desafio 4: Replicabilidade, Sugestões e Trabalho Comunitário"
output: distill::distill_article
---

```{r, echo=F}
knitr::opts_chunk$set(echo = F, eval=F, highlight=T)
```


<style>
div.purple { background-color:#9e9ac8; border-radius: 5px; padding: 20px;}
</style>

<div class = "purple">
O prazo para entregar Desafio 4 por email com título “[FLS6397] - D4” à minha conta é **14h, 18/06/2020**, antes da aula. Por favor entregue (i) o arquivo .Rmd, e (ii) o arquivo .html.
</div>

<br>

## Instruções

O seu objetivo é replicar, entender, e aperfeiçoar o código de um colega anônimo da disciplina submetido para Desafio 3. A tarefa é *construtiva* e não uma oportunidade para criticar ou impor as suas preferências - por favor pense no tipo de sugestão que você queria receber antes de começar.

Enviarei o .rmd de outro colega anônimo para o seu email, de modo que sua tarefa é seguir os próximos passos abaixo. Antes do prazo, você deve submeter novos .rmd e .html, incluindo as mudanças realizadas no código *e comentários (com #)*. Por fim, vou passar o seu arquivo para o autor do código, para que ele/a consiga aproveitar das suas sugestões. Não se preocupe: também manterei dua identidade anônima.

## Roteiro

1. Primeiro, baixe o .rmd e compile ele com 'knit'. Lembre-se de verificar que os bancos de dados externos estãao presentes na pasta apropriada. Observe e anote em comentários se existe algum impedimento para compilar o documento, ou alguma mudança que precisa ser feita no código. Isto é um teste importante de reprodutibilidade.

2. Leia o código e avalie se tudo faz sentido. Veja também se o autor utilizou funções ou algum código desconhecido para você. Rode o código interativamente para entender cada passo, e anote com comentários se houver alguma linha que não ficou claro ou se deveria ser explicado melhor com comentários pelo autor original.

3. Compare *a sua submissão* de Desafio 3 com o arquivo recebido, identifique as diferenças, e se e como elas afetam os resultados. Sugira melhorias que possam ser aproveitadas do seu código, e documente eles com comentários. (Para uso pessoal, identifique as melhorias qu você poderia aproveitar para o seu código de Desafio 3.)

4. (Apenas depois do item 3:) Compare *as respostas sugeridas* no site da disciplina com o arquivo recebido, identificando com cuidado as diferenças e os erros. Onde existe divergência (e não é erro meu!) resolva o problema, melhore o código, e adicione um comentário (com #) descrevendo a fonte do erro e a sua solução.

5. Avalie o HTML gerado pelo arquivo recebido e sugira melhorias para deixar ele mais claro, bonito e simples. Por exemplo, a divisão entre questões e respostas fica claro? As tabelas estão bem formatadas ou em código bruto? Há alugma tabela que poderia ser omitida, ou ter o número de linhas/colunas limitado? É necessário ajustar as opcões de chunks para remover mensagens ou código desnecessário? As respostas calculadas estão inseridas como código in-line?

6. Finalmente, foi um Desafio sobre gráficos, então avalie se cada gráfico contém toda a informação necessária para entendê-lo, e mostra um resultado claro e bonito. Sugira melhorias nos gráficos como títulos nos eixos, escalas de cores mais apropriados, temas apropriadas, etc.

7. Dê mais uma olhada nos seus comentários para confirmar que eles estão claros, informativos, e construtivos. 

8. Verifique que o resultado dos seus ajustes é um arquivo de .rmd claro, bem comentado, facilmente reproduzível e que pode ser compilado sem erro.

